In [3]:
import pandas
import duckdb

In [8]:
# Connect to your persistent database file
conn = duckdb.connect("ehr.duckdb")

In [20]:
conn.execute("select * from information_schema.tables").df()

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action,TABLE_COMMENT
0,ehr,main,hno_info,BASE TABLE,None,None,None,None,None,YES,NO,None,None
1,ehr,main,ip_flwsht_meas,BASE TABLE,None,None,None,None,None,YES,NO,None,None
2,ehr,main,ip_frequency,BASE TABLE,None,None,None,None,None,YES,NO,None,None
3,ehr,main,medical_hx,BASE TABLE,None,None,None,None,None,YES,NO,None,None
4,ehr,main,order_med,BASE TABLE,None,None,None,None,None,YES,NO,None,None
5,ehr,main,order_proc_awv,BASE TABLE,None,None,None,None,None,YES,NO,None,None
6,ehr,main,order_results,BASE TABLE,None,None,None,None,None,YES,NO,None,None
7,ehr,main,patient,BASE TABLE,None,None,None,None,None,YES,NO,None,None
8,ehr,main,pat_enc,BASE TABLE,None,None,None,None,None,YES,NO,None,None
9,ehr,main,pat_enc_dx,BASE TABLE,None,None,None,None,None,YES,NO,None,None
10,ehr,main,problem_list,BASE TABLE,None,None,None,None,None,YES,NO,None,None
11,ehr,main,provider,BASE TABLE,None,None,None,None,None,YES,NO,None,None
12,ehr,main,rxnorm_codes,BASE TABLE,None,None,None,None,None,YES,NO,None,None
13,ehr,main,surgical_hx,BASE TABLE,None,None,None,None,None,YES,NO,None,None
14,ehr,main,v_diagnosis,VIEW,None,None,None,None,None,NO,NO,None,None
15,ehr,main,v_encounter,VIEW,None,None,None,None,None,NO,NO,None,None
16,ehr,main,v_lab_order,VIEW,None,None,None,None,None,NO,NO,None,None
17,ehr,main,v_lab_result,VIEW,None,None,None,None,None,NO,NO,None,None
18,ehr,main,v_medication,VIEW,None,None,None,None,None,NO,NO,None,None
19,ehr,main,v_vitals,VIEW,None,None,None,None,None,NO,NO,None,None

In [21]:
conn.execute("select * from v_encounter").df()

,PAT_ENC_CSN_ID,PAT_ID,PAT_MRN_ID,CONTACT_DATE,APPT_TIME,DEPARTMENT_NAME,LOC_NAME,INSURANCE,PAT_NAME,BIRTH_DATE,PAT_AGE,SEX_NAME,VISIT_PROV_ID,visit_prov_name,visit_prov_specialty,primary_icd10,primary_dx
0,ENC38381556,P200001,MRN6695111,2026-05-09,2026-05-09 14:20:00,Internal Medicine Clinic,Main Campus,commercial,"Erickson, Savannah",1981-08-04,44,Female,PROV0005,Daniel Mills,Cardiology,I11.9,"Hypertensive Heart Disease, Unspecified"
1,ENC51588692,P200002,MRN5658579,2025-09-22,2025-09-22 12:03:00,Psychiatry Clinic,Behavioral Health Center,medicaid,"Brown, Todd",1993-05-19,33,Male,PROV0004,Dr. Joseph Costa,Internal Medicine,I10,Essential Hypertension
2,ENC63883141,P200003,MRN4396157,2025-08-18,2025-08-18 09:55:00,GI / Gastroenterology,Specialty Pavilion,medicare,"Wilson, Kelly",1998-07-04,27,Female,PROV0011,Tyler Hill,Psychiatry,F32.9,"Major Depressive Disorder, Unspecified"
3,ENC50418450,P200003,MRN4396157,2025-06-13,2025-06-13 12:21:00,Psychiatry Clinic,Behavioral Health Center,medicare,"Wilson, Kelly",1998-07-04,27,Female,PROV0009,Tina Wells,Internal Medicine,F32.9,"Major Depressive Disorder, Unspecified"
4,ENC54171683,P200004,MRN6757862,2026-04-14,2026-04-14 12:35:00,Endocrinology,Specialty Pavilion,medicare,"Cervantes, Stephen",2006-09-07,19,Male,PROV0002,Michael Lee,Endocrinology,E11.51,Type 2 DM with Diabetic Peripheral Neuropathy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,ENC66845724,P200097,MRN6501531,2026-04-13,2026-04-13 14:35:00,OB/GYN Clinic,Women's Health Pavilion,medicare,"Lang, Amy",2007-06-12,18,Female,PROV0009,Tina Wells,Internal Medicine,I11.9,"Hypertensive Heart Disease, Unspecified"
149,ENC58472851,P200098,MRN8074733,2025-08-21,2025-08-21 10:26:00,OB/GYN Clinic,Women's Health Pavilion,medicaid,"Beck, Sally",1991-02-23,35,Female,PROV0004,Dr. Joseph Costa,Internal Medicine,F41.9,"Anxiety Disorder, Unspecified"
150,ENC72502474,P200098,MRN8074733,2025-12-21,2025-12-21 08:20:00,Endocrinology,Specialty Pavilion,medicaid,"Beck, Sally",1991-02-23,35,Female,PROV0012,Dean Washington Jr.,Pulmonology,F41.9,"Anxiety Disorder, Unspecified"
151,ENC61937043,P200099,MRN8091954,2025-11-28,2025-11-28 17:34:00,Pulmonology Clinic,Lung Health Pavilion,commercial,"Davis, Rebekah",1951-10-17,74,Female,PROV0010,Wendy Cortez,Cardiology,I10,Essential Hypertension
152,ENC61472178,P200100,MRN5307103,2026-04-15,2026-04-15 13:09:00,OB/GYN Clinic,Women's Health Pavilion,commercial,"Wilcox, Tommy",1975-03-01,51,Male,PROV0006,Margaret Schneider,Neurology,E78.1,Pure Hypertriglyceridaemia

In [15]:
conn

In [22]:
# Remember to close the connection when done
conn.close()